### ISSUE TITLE
Getting error when running last command on terminal

### ISSUE THREAD

**Issue by Eugology** [snaco/steam-library-fix#1]
When executing fix_steam
I get:
File "/home/hazarlmf/steam_library_fix.py", line 10, in <module>
    library_games = os.listdir(f'{library_path}common/')
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/Gravemind/SteamLibrary/steamappscommon/'
What can it be?

**Comment by snaco** [comment]
ah yeah, it looks like the library path you provided was ```/mnt/Gravemind/SteamLibrary/steamapps``` you could try again with ```/mnt/Gravemind/SteamLibrary/steamapps/``` instead for now. I can also add a patch to the script which will add the slash at the end if it is missing. Thanks for pointing that out!

**Comment by Eugology** [comment]
Done apparently worked I think needed to add '/' before the common and compaptdata on the py file. Got this on the terminal:
urrent games ready to play:
	Proton - Experimental
	SteamLinuxRuntime_soldier
	Steam.dll
	Steamworks Shared
	Overcooked
Games to patch:
	Left 4 Dead 2
	Destroy All Humans!
	Haydee
	Lego Star Wars Saga
	Counter-Strike Global Offensive
	Yu-Gi-Oh!  Master Duel

**Comment by snaco** [comment]
Nice! Let me know if any other issues pop up!
